#!/bin/bash
#tab=containers
#section=plex
#name=Build Plex

docker run \
-d \
--name plex \
-p 32400:32400/tcp \
-p 3005:3005/tcp \
-p 8324:8324/tcp \
-p 32469:32469/tcp \
-p 1900:1900/udp \
-p 32410:32410/udp \
-p 32412:32412/udp \
-p 32413:32413/udp \
-p 32414:32414/udp \
-e TZ="Europe/Helsinki" \
-e PLEX_CLAIM="claim-JVN6Y9ffzmioYMG35B8E" \
-e ADVERTISE_IP="http://192.168.1.123:32400/" \
-h PlexMediaServer \
-v /mnt/ssd/appdata/plex-media-server/config:/config \
-v /mnt/ssd/appdata/plex-media-server/transcode:/transcode \
-v /mnt/hdd/media:/data \
plexinc/pms-docker
