#!/bin/bash
#tab=Containers
#section=Chia
#name=Build Chia
#icon=https://d1dipv7bkc8ff3.cloudfront.net/87/31/68/873168A.jpg

docker run \
  --name chia \
  -d ghcr.io/chia-network/chia:latest \
  -v /mnt/ssd/appdata/chia:/root/.chia \
  -v /mnt/sdd/Chia/plotting:/plotting \
  -v /mnt/hdd/Chia/plots:/plots
