#!/bin/bash
#tab=Hardware
#section=Storage
#name=Start BTRFS HDD Array
#icon=https://i.imgur.com/dGuRY9L.gif

hddStandbyTime=242 #0=off, 1-240=x5sec,241-251=x30min

hddIds=(
  "ata-HGST_HUS726T6TALE6L4_V9GNUENL"
  "ata-Hitachi_HUA723020ALA641_YFHU8JWA"
  "ata-Hitachi_HUA723020ALA641_YFHUL40A"
  "ata-Hitachi_HUA723020ALA641_YGHSMJRA"
  "ata-ST2000DM001-1ER164_Z4Z1HC79"
  "ata-TOSHIBA_DT01ACA300_64M3RLAGS"
  "ata-TOSHIBA_DT01ACA300_Y3NDBB5GS"
  "ata-TOSHIBA_HDWE160_969AK7WBF56D"
  "ata-TOSHIBA_HDWE160_96P4K5QXF56D"
  "ata-TOSHIBA_HDWE160_Y7PUK2HVF56D"
  "ata-TOSHIBA_HDWN160_60H7K23YFAXG"
  "ata-WDC_WD20EARS-00J2GB0_WD-WCAYY0291350"
  "ata-WDC_WD20EARS-00MVWB0_WD-WCAZA5438953"
)

echo "Starting and mounting HDD BTRFS array"
mount /dev/disk/by-id/ata-HGST_HUS726T6TALE6L4_V9GNUENL /mnt/hdd

echo "Set disk standby timer"
for hdd in ${hddIds[@]}; do
  hdparm -S$hddStandbyTime /dev/disk/by-id/$hdd
done

echo "Exporting /mnt/hdd via NFS"
exportfs -o rw *:/mnt/hdd
