#!/bin/bash
#tab=Hardware
#section=Storage
#name=Stop BTRFS SSD Array
#icon=https://i.imgur.com/qIwia.gif

echo "Remove /mnt/ssd NFS export"
exportfs -u /mnt/ssd

echo "Stopping and unmounting SSD BTRFS array."
umount /mnt/ssd
