#!/bin/bash
#tab=storage
#section=main
#name=Storage Devices

function mountHDD {
  echo "Starting and mounting HDD BTRFS array"
  mount /dev/disk/by-id/${hddIds[0]} $hddMountDir
}

function umountHDD {
  echo "Stopping and un-mounting HDD BTRFS array."
  umount $hddMountDir
}

function mountSSD {
  echo "Starting and mounting SSD BTRFS array."
  mount /dev/disk/by-id/${ssdIds[0]} $ssdMountDir
}

function umountSSD {
  echo "Stopping and un-mounting SSD BTRFS array."
  umount $ssdMountDir
}

function setDeviceStandBy {
  echo "Set disk standby timer"
  for hdd in ${hddIds[@]}; do
    hdparm -S$hddStandbyTime /dev/disk/by-id/$hdd
  done
}

function storageCmd {
  case $1 in
    --start)
      mountSSD
      mountHDD
      setDeviceStandBy
      ;;
    --stop)
      umountSSD
      umountHDD
      ;;
    --start-hdd)
      mountHDD
      setDeviceStandBy
      ;;
    --stop-hdd)
      umountHDD
      ;;
    --start-ssd)
      mountSSD
      ;;
    --stop-ssd)
      umountSSD
      ;;
  esac
}
