#!/bin/bash
#tab=System
#section=Test
#name=Test Script
#icon=https://media.giphy.com/media/mFwqFZx1HxfQ4hwkz9/giphy.gif

echo "Starting test script"
sleep 3s
ls 
echo "list complete"
sleep 3s
cat /proc/cpuinfo
sleep 3s
ls 
echo "Test Complete"
