#!/bin/bash
#tab=VMs
#section=windows
#name=Tiia VM

for param in "$@"; do
[ $param == "on" ] && qemu-system-x86_64 \
-enable-kvm \
-cpu host \
-smp 6,sockets=1,cores=6,threads=1 \
-m 24576 \
-drive if=pflash,format=raw,readonly,file=/usr/share/edk2-ovmf/OVMF_CODE.fd \
-drive if=pflash,format=raw,file=/usr/share/edk2-ovmf/OVMF_VARS.fd \
-drive id=disk,file=/dev/disk/by-id/ata-Samsung_SSD_850_PRO_256GB_S1SUNSAFB16925P,format=raw,if=none \
-device ahci,id=ahci \
-device ide-hd,drive=disk,bus=ahci.0 \
-device virtio-net,netdev=vmnic -netdev user,id=vmnic \
-device vfio-pci,host=42:00.0,x-vga=on \
-device vfio-pci,host=42:00.1 \
-device vfio-pci,host=43:00.0 \
-device vfio-pci,host=43:00.2 \
-device vfio-pci,host=43:00.3 \
-vga none \
-boot c
done
