#!/bin/bash
#tab=passthrough
#section=vfio
#name=vfio
#icon=https://cdn.onlinewebfonts.com/svg/img_486237.png

function vfioBind {
  modprobe vfio-pci
  for dev in "$vfioDevices" do
    vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
    device=$(cat /sys/bus/pci/devices/$dev/device)
    if [ -e /sys/bus/pci/devices/$dev/driver ]; then
      echo $dev > /sys/bus/pci/devices/$dev/driver/unbind
    fi
    echo $vendor $device > /sys/bus/pci/drivers/vfio-pci/new_id
  done
}

function listIOMMU {
  for iommu_group in $(find /sys/kernel/iommu_groups/ -maxdepth 1 -mindepth 1 -type d); do 
    echo "IOMMU group $(basename "$iommu_group")"; 
    for device in $(ls -1 "$iommu_group"/devices/); do 
      echo -n $'\t'; 
      lspci -nns "$device"; 
    done; 
  done
}

function vfioCmd {
  case $1 in
    --bind)
      vfioBind
      ;;
    --list)
      listIOMMU
      ;;
  esac
}
